<a href="https://colab.research.google.com/github/lnikam1811/Learning_PyTorch/blob/master/PyTorch_Fundamentals_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Create a random tensor with shape `(7,7)`

In [1]:
import torch

A = torch.rand(size=(7, 7))
A

tensor([[0.1304, 0.3883, 0.2505, 0.2305, 0.0554, 0.9433, 0.3859],
        [0.2043, 0.2932, 0.3435, 0.5904, 0.0692, 0.8082, 0.6674],
        [0.9404, 0.4283, 0.8705, 0.3838, 0.3238, 0.9270, 0.4399],
        [0.0316, 0.0435, 0.7070, 0.0088, 0.4973, 0.4332, 0.6592],
        [0.4227, 0.7970, 0.7590, 0.7013, 0.6075, 0.8798, 0.1880],
        [0.5513, 0.5549, 0.2753, 0.8912, 0.4791, 0.3956, 0.1389],
        [0.8311, 0.5892, 0.0235, 0.9175, 0.2452, 0.5833, 0.6253]])

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
B = torch.rand(size=(1,7))
dot_AB = torch.matmul(A, B.T)
dot_AB

tensor([[1.2199],
        [1.2957],
        [1.8263],
        [0.8634],
        [1.8186],
        [1.3081],
        [1.7400]])

# 4. Set the random seed to 0 and do 2 & 3 over again.

In [8]:
import random
random.seed(0)
C = torch.rand(7, 7)
D = torch.rand(1, 7)
dot_CD = torch.matmul(C, D.T)
dot_CD, dot_CD.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [12]:
torch.cuda.seed()

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
`Device: cuda`
`(tensor([[0.0290, 0.4019, 0.2598],`
         `[0.3666, 0.0583, 0.7006]], device='cuda:0'),`
 `tensor([[0.0518, 0.4681, 0.6738],`
         `[0.3315, 0.7837, 0.5631]], device='cuda:0'))`

In [14]:
import torch 
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

A = torch.rand(size=(2, 3))
B = torch.rand(size=(2, 3))

A_gpu = A.to(device)
B_gpu = B.to(device)

print(A_gpu)
print(B_gpu)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```         





In [16]:
dot_AB = torch.matmul(A, B.T)
dot_AB, dot_AB.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]), torch.Size([2, 2]))

# 8. Find the maximum and minimum values of the output of 7.

In [17]:
torch.max(dot_AB), torch.min(dot_AB)

(tensor(0.5617), tensor(0.3647))

# 9. Find the maximum and minimum index values of the output of 7.

In [18]:
torch.argmax(dot_AB), torch.argmin(dot_AB)

(tensor(3), tensor(0))

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
```
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
torch.manual_seed(7)
X = torch.rand(size=(1,1,1,10))
new_x = torch.squeeze(X)
X, X.shape, new_x, new_x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))